### ISSUE TITLE
NullPointerException in TrafficMapActivity$CalloutsOverlayTask.onPreExecute

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-android-app#24]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.maps.Projection com.google.android.gms.maps.GoogleMap.getProjection()' on a null object reference at gov.wa.wsdot.android.wsdot.ui.trafficmap.**TrafficMapActivity$CalloutsOverlayTask.onPreExecute**(TrafficMapActivity.java:628)
at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:591)
at android.os.AsyncTask.execute(AsyncTask.java:539)
at gov.wa.wsdot.android.wsdot.ui.trafficmap.**TrafficMapActivity.onResume**(TrafficMapActivity.java:193)

**Comment by waynedyck** [comment]
This is related to Issue #34. More details are provided there.
