### ISSUE TITLE
Runtime error when accessing Amtrak Cascades schedules

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-android-app#33]
**java.lang.NullPointerException**
at gov.wa.wsdot.android.wsdot.ui.amtrakcascades.AmtrakCascadesSchedulesActivity.requestLocationUpdates(AmtrakCascadesSchedulesActivity.java:383)
at gov.wa.wsdot.android.wsdot.ui.amtrakcascades.AmtrakCascadesSchedulesActivity.onConnected(AmtrakCascadesSchedulesActivity.java:340)

**Comment by waynedyck** [comment]
Error occurs when user has **Location Services** disabled on their phone.
