### ISSUE TITLE
AmtrakCascadesScheduleItem.getTrainName() on a null object reference

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-android-app#37]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String gov.wa.wsdot.android.wsdot.shared.AmtrakCascadesScheduleItem.getTrainName()' on a null object reference
at gov.wa.wsdot.android.wsdot.ui.amtrakcascades.AmtrakCascadesSchedulesDetailsFragment$ScheduleAdapter.getView(AmtrakCascadesSchedulesDetailsFragment.java:863)

**Comment by waynedyck** [comment]
java.lang.NullPointerException
at gov.wa.wsdot.android.wsdot.ui.amtrakcascades.AmtrakCascadesSchedulesDetailsFragment$ScheduleAdapter.getView(AmtrakCascadesSchedulesDetailsFragment.java:722)

**Comment by loganSims** [comment]
Merged with #92
