### ISSUE TITLE
BadParcelableException on android 2.3.x Devices.

### ISSUE THREAD

**Issue by loganSims** [WSDOT/wsdot-android-app#68]
`android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.design.widget.AppBarLayout$Behavior$SavedState`

Two reports from app version 4.1.0 on Android 2.3.3 and 2.3.7.
Looks like a [bug with the support libraries.](https://code.google.com/p/android/issues/detail?id=196430)

##### Full Stack Trace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{gov.wa.wsdot.android.wsdot/gov.wa.wsdot.android.wsdot.ui.home.HomeActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.design.widget.AppBarLayout$Behavior$SavedState
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1651)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1667)
	at android.app.ActivityThread.access$1500(ActivityThread.java:117)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:935)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3689)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.design.widget.AppBarLayout$Behavior$SavedState
	at android.os.Parcel.readParcelable(Parcel.java:1958)
	at android.os.Parcel.readParcelableArray(Parcel.java:1997)
	at android.support.design.widget.CoordinatorLayout$SavedState.<init>(CoordinatorLayout.java:2604)
	at android.support.design.widget.CoordinatorLayout$SavedState$1.createFromParcel(CoordinatorLayout.java:2639)
	at android.support.design.widget.CoordinatorLayout$SavedState$1.createFromParcel(CoordinatorLayout.java:2636)
	at android.support.v4.os.ParcelableCompat$CompatCreator.createFromParcel(ParcelableCompat.java:51)
	at android.os.Parcel.readParcelable(Parcel.java:1981)
	at android.os.Parcel.readValue(Parcel.java:1846)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:2112)
	at android.os.Parcel.readSparseArray(Parcel.java:1568)
	at android.os.Parcel.readValue(Parcel.java:1903)
	at android.os.Parcel.readMapInternal(Parcel.java:2083)
	at android.os.Bundle.unparcel(Bundle.java:208)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:1167)
	at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1666)
	at android.app.Activity.onRestoreInstanceState(Activity.java:844)
	at android.app.Activity.performRestoreInstanceState(Activity.java:816)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1096)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1629)
	... 11 more
```

**Comment by loganSims** [comment]
It looks like this will not be fixed anytime soon. The following is from [google code issue #196430](https://code.google.com/p/android/issues/detail?id=196430)

> This issue could not be reproduced in Marshmallow builds. At this point, our eng teams are not prioritizing changes on earlier releases. Please do let us know if you encounter this issue on 6.0+.
